### ISSUE TITLE
Static IP-Addresse funktioniert nicht

### ISSUE THREAD

**Issue by GasCan1234** [jp112sdl/SonoffHM#1]
Wenn ich über den WLAN-Konfigurator die statische IP-Addresse setze verbindet sich das Sonoff-Gerät zwar mit meinen WLAN aber es setzt nicht die IP richtig.

**Comment by jp112sdl** [comment]
Aufgrund einer zu kleinen Reservierung für die Länge von IP/NM/GW wurde die letzte Stelle abgeschnitten. Ist nun gefixt.

**Comment by GasCan1234** [comment]
Funktioniert bei mir noch nicht...

### Conifugration

*WM: Handle root
*WM: Sent config page
*WM: WiFi save
*WM: Parameter
*WM: ccu
*WM: 192.168.10.1
*WM: Parameter
*WM: sonoff
*WM: Test
*WM: Parameter
*WM:
*WM:
*WM: Parameter
*WM: custom_ip
*WM: 192.168.10.11
*WM: Parameter
*WM: custom_netmask
*WM: 255.255.255.0
*WM: Parameter
*WM: custom_gw
*WM: 192.168.10.1
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...

### Reboot

mounting FS...
mounted file system
/config.json not found.
*WM: Adding parameter
*WM: ccu
*WM: Adding parameter
*WM: sonoff
*WM: Adding parameter
*WM:
*WM: Adding parameter
*WM: custom_ip
*WM: Adding parameter
*WM: custom_netmask
*WM: Adding parameter
*WM: custom_gw
*WM:
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster

**Comment by jp112sdl** [comment]
Das sieht ja fast nach einem Speicherfehler am Sonoff aus.

```/config.json not found.```

Die Konfigurationsdatei ist nach dem Reboot nicht vorhanden.
Ich habe zurzeit keinen Sonoff zum Testen.

Mit einem Wemos D1 mini funktioniert der Code.
